### ISSUE TITLE
Ability to Get Weather Warnings 

### ISSUE THREAD

**Issue by BillyFKidney** [briis/weatherflow_forecast#10]
**Is your feature request related to a problem? Please describe.**
There is no easy method to receive weather warnings in Home Assistant. 

**Describe the solution you'd like**
I would like the ability to see any weather warnings for my weather station. It would be helpful if they can be sorted by type (wind, air quality, flood, hurricane, etc) and severity. 
![image](https://github.com/briis/weatherflow_forecast/assets/65253277/349c39c0-c9c8-457c-a2db-c6d1f6bb8835)

![image](https://github.com/briis/weatherflow_forecast/assets/65253277/2c8af796-5aeb-4440-a212-8aa5b70cb4b4)

**Describe alternatives you've considered**
I have attempted to use WAQI but it is not reliable. 

**Additional context**
The ability to know the type of warning would be helpful because we receive snow warnings for the nearby mountains (aka elevation above 5,000 ft) which are not applicable to us.

**Comment by briis** [comment]
Unfortunately this type of data is not available in the API. I assume WeatherFlow is pulling this data from a 3rd party depending on the location of the Weather Station, and they do not include the data directly in the API.
So I cannot deliver this data with this integration, as much as I would like to do.

**Comment by BillyFKidney** [comment]
Understood, if you have any suggestions please let me know.

**Comment by briis** [comment]
I do have another relatively new Integration called [VisualCrossing](https://github.com/briis/visualcrossing). They do make Weather Alerts available. Your question made me raise an issue (to myself) to make use of that data, so eventually that might  be an option for you. Follow the issue on Github and I will post updates there once it is ready for testing.

Just one note: The issue with weather alerts is that they only occur sporadic, so I need to find a few locations in the world that have more frequent weather alerts than quite Denmark to get some test data to work with.

**Comment by BillyFKidney** [comment]
Riverside County CA (92234) USAWind warnings and air quality alerts due to dust are constant- Billy -On Oct 12, 2023, at 3:50 AM, Bjarne Riis ***@***.***> wrote:﻿
I do have another relatively new Integration called VisualCrossing. They do make Weather Alerts available. Your question made me raise an issue (to myself) to make use of that data, so eventually that might  be an option for you. Follow the issue on Github and I will post updates there once it is ready for testing.
Just one note: The issue with weather alerts is that they only occur sporadic, so I need to find a few locations in the world that have more frequent weather alerts than quite Denmark to get some test data to work with.

**Comment by briis** [comment]
I understand why you would want everything in one integration, but for the US, it seems that NWS is the best Weather Alert provider. Have you had a look at that: https://www.home-assistant.io/integrations/nws/

**Comment by davethetallguy** [comment]
Bill, sorry for the late reply, but in case you're still working on this:

I set up a sensor for using the NWS core integration for Orange County. I then send alerts directly to my phone via the mobile app:

```
alias: NWS OC Weather Alert with URL
description: >-
  Stripped down version of the NWS integration provided example automation for
  notifications
trigger:
  - platform: state
    entity_id: sensor.nws_oc_alerts
condition:
  - condition: and
    conditions:
      - condition: template
        value_template: "{{states('sensor.nws_oc_alerts') | int > 0}}"
      - condition: template
        value_template: "{{ trigger.to_state.state|int > trigger.from_state.state|int }}"
action:
  - service: notify.mobile_app_david_s_phone
    data:
      title: NWS Orange County Weather Alert
      message: >-
        {{
        ((states.sensor.nws_oc_alerts.attributes.values()|list)[8]).split('\n')[0]
        }}
      data:
        url: homeassistant://navigate/lovelace/oc-weather
mode: single
initial_state: "on"
```

Note the "data: url:" code near the bottom takes me to a card on my dashboard. It can be deleted if you don't want to code up a card as well.  

Change the mobile_app entity to your phone.  

I've got a similar alert configured for San Diego and Los Angeles counties too. Multiples work just fine.

Good luck!
