### ISSUE TITLE
Incorrect daily max for 'today' sensors when using long term statistics

### ISSUE THREAD

**Issue by jata1** [briis/weatherflow_forecast#102]
I use long term statistics (max) to chart daily rainfall from the daily rain sensor over an extended period (e.g. last 30 days). If the max rainfall for the previous day is greater than the current day, then the statistics returns the max from the previous day. So I think the statistic is resetting just after midnight and this creates a 'erroneous statistic' for today's max. 

create a chart using apex charts with 2 series based on the daily rain sensor.
for one series, use group_by day max
for the other use statistics by day max
look for days/pattern where the there is a different max for a day

here is a my chart yaml and screenshot to make it easier to reproduce

```
type: custom:apexcharts-card
apex_config:
  xaxis:
    labels:
      format: ddd dd/MM
      trim: false
      offsetY: -5
      style:
        fontWeight: 400
        fontSize: 10
  legend:
    show: true
    labels:
      style:
        fontWeight: 400
        fontSize: 10
all_series_config:
  stroke_width: 1
  opacity: 0.1
  show:
    offset_in_name: false
    legend_value: false
    extremas: false
    name_in_header: false
    datalabels: false
graph_span: 20d
span:
  end: day
header:
  show: true
  title: Rainfall History
  show_states: false
  colorize_states: true
yaxis:
  - id: rain
    min: 0
    max: ~120
    decimals: 0
    apex_config:
      tickAmount: 6
      title:
        rotate: -90
        text: Rain (mm)
        style:
          fontWeight: 400
          fontSize: 9
    show: true
    opposite: false
series:
  - entity: sensor.undercliffe_sensors_precipitation_today
    name: Rain (group_by)
    color: blue
    opacity: 0.4
    yaxis_id: rain
    type: column
    group_by:
      func: max
      duration: 1d
  - entity: sensor.undercliffe_sensors_precipitation_today
    name: Rain (stats)
    color: grey
    opacity: 0.4
    yaxis_id: rain
    type: column
    statistics:
      type: max
      period: day
      align: start

```
![image](https://github.com/briis/weatherflow_forecast/assets/23280705/27903a38-3e74-4e82-91b6-eef49a0599a1)

This is only an issue when you want to plot this data over an extended period - where LTS are needed.

If you didn't notice from my chart, there has been a 'rain event' here in sydney over the last couple of days!
