### ISSUE TITLE
weather.forecast entity not compatible with weather forecast cards

### ISSUE THREAD

**Issue by Tillsy** [briis/weatherflow_forecast#53]
**Describe the bug**
The new Weatherflow integration has a forecast entity that combines a lot of elements together, particularly daily AND hourly forecasting.  This is not working with any of the weather cards which seem to get confused about this entity.

**To Reproduce**
1. Install any weather forecast card
2. Set the entity to be the weather.forecast entity
3. Observe the 5-day forecast section of the card, any weather forecast card, disappears
4. Change the entity to be the weather.weatherflow_day_based_forecast of the old Weatherflow integration
5. Observe the 5-day forecast section of any weather forecast card appears and works correctly.

**Expected behavior**
Weather cards should show a 5-day forecast when pointing at the weather.forecast entity.

**Screenshots**
Screenshot of the animated weather card using the old weather.weatherflow_day_based_forecast:
<img width="296" alt="image" src="https://github.com/briis/weatherflow_forecast/assets/103569790/10cae895-736b-4a54-ac50-a82c5bcbe01d">

Screenshot of the animated weather card using the new weather.forecast entity:
<img width="307" alt="image" src="https://github.com/briis/weatherflow_forecast/assets/103569790/a991be5f-1d91-41d3-8bfc-8ac146e15ba4">

**Additional context**
This has come about with the replacement Weatherflow integration.

**Comment by briis** [comment]
This is not an error with this Integration, it is the Animated Weather Card that does not support the new format, so you should ask the author of that card to update it.
If you use the `weather.forecast` entity on the default weather card, you will see that it works.

The reason it does not work is that as of march 2024, the Forecast Attributes are no longer supported, and most older Weather Cards look for these attributes to build the forecast. This weather entity has already removed them.

**Comment by Tillsy** [comment]
This happens with ALL the weather cards though.  This all started with the built-in weather-card which I've been using for years.

I then cycled through a whole bunch of various ones in HACS including the animated weather card which is how I came across it, and they too would fail with the new Weatherflow integration.  They all work with the old one.

Here's is the YAML showing the built-in one...
  - type: weather-forecast
    entity: weather.weatherflow_day_based_forecast
    name: Sheidow Park
    show_forecast: true
    
    Here is a screenshot:
    
<img width="474" alt="image" src="https://github.com/briis/weatherflow_forecast/assets/103569790/4e8acb10-b315-4357-a7d1-fd33c71609bc">

Now I change to to this new Weatherflow integration:
  - type: weather-forecast
    entity: weather.forecast_tricorder
    name: Sheidow Park
    show_forecast: true
    
And here is the screenshot:
<img width="466" alt="image" src="https://github.com/briis/weatherflow_forecast/assets/103569790/8ba89521-3437-40a2-aca4-f5223e713e08">

So are you saying even Home Assistant's own weather card is at fault?  Home Assistant itself shows the new forecast entity just fine so it does seem that way I guess, just seems odd even they haven't updated as this was announced months ago.

**Comment by disruptivepatternmaterial** [comment]
I think I am seeing something similar...how are you supposed to access the forecast data, say hourly now? I can see it, but there is not way to reference it in templates or other code situation. This has caused all my esphome devices to break because they are looking for the old array format...so what is the new format?

**Comment by briis** [comment]
The new format was introduced in [HA 2023.9](https://www.home-assistant.io/blog/2023/09/06/release-20239/#weather-forecast-service) where it also states that the Attributes will be removed as of HA 2024.3.
If you use the built-in [Weather Card](https://www.home-assistant.io/dashboards/weather-forecast/) you have to enable to show the Forecast and then select what type of Forecast you want to show.

Both of the above are described in the links I have added.

Templating the new format is a bit more tricky and not very well described, except that they introduced a new service called `weather.get_forecasts`. You can play with that in the Developer tools, but this service extracts the forecast data, for the type you need. This integration supports Daily and Hourly forecast.

Here is an example of a Template sensor, that runs every hour, calls the service, and then extracts the daily high temeprature from the forecast.

Hope all this helps.

```yaml
- trigger:
    - platform: time_pattern
      hours: /1
  action:
    - service: weather.get_forecasts
      target:
        entity_id: weather.weather_roskilde
      data:
        type: daily
      response_variable: daily_forecast
  sensor:
    - name: Weather Temperature High
      unique_id: ef4c1d45-9d47-4a62-b91c-3953b0d5b041
      icon: mdi:thermometer-chevron-up
      unit_of_measurement: C
      state: >
        {% set forecast = daily_forecast['weather.weather_roskilde']['forecast'] %}
        {{ forecast[0].temperature | float(0) | round(1) }}
 ````
