### ISSUE TITLE
Hourly weather forecast - request

### ISSUE THREAD

**Issue by chiefcomm** [briis/weatherflow_forecast#55]
1st up a huge thanks for the integration and continued support.

Throwing this out there - do you have any thought to bring the hourly forecast to this new integration?   I found it very useful in the past and would love to see it return.

![image](https://github.com/briis/weatherflow_forecast/assets/45157523/b849166b-f003-49f5-a784-ea91946bf1b1)

**Comment by briis** [comment]
Hourly Forecast has been available since day 1. Just since HA 2023.9 there has been some significant changes to how Weather entities and Lovelace cards work. I had another user with similar issues, please have a look on my reply to him: https://github.com/briis/weatherflow_forecast/issues/53#issuecomment-1868213211

Let me know if this answers your question?

**Comment by briis** [comment]
Just to show you how this can be used. The below is the built-in Weatherforecast card, configured with this integration in hourly mode:

![image](https://github.com/briis/weatherflow_forecast/assets/24776272/a6ee2716-a967-4e8a-a452-503baa260f93)

**YAML code of the above**
```yaml
show_current: true
show_forecast: true
type: weather-forecast
entity: weather.forecast_toftebuen
forecast_type: hourly
````
